version: "3"
services:
  marketplace:
    build: .
    ports:
      - "4000:80"
    volumes:
      - .:/app
    networks:
      - books-net
    depends_on:
      - postgres
    command: python main.py

  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: astro
      POSTGRES_PASSWORD: astro
      POSTGRES_DB: books_marketplace
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - books-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "astro"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  postgres-db-volume:

networks:
  books-net:
