version: "3"
services:
  marketplace:
    build: .
    ports:
      - "4000:80"
    volumes:
      - .:/app
    command: python main.py
    depends_on:
      - postgres

  postgres:
    image: postgres:14.0
    environment:
      POSTGRE_USER: astro
      POSTGRE_PASSWORD: astro
      POSTGRE_DB: books_marketplace
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "astro"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  postgres-db-volume:
